name: cuvs_cagra
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
  search: cuvs_bench.config.algos.constraints.cuvs_cagra_search
groups:
  base:
    build:
      graph_degree: [64]
      intermediate_graph_degree: [96]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [512]
      search_width: [1]
